# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Deploy
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    pool: Default
    environment: EnvName
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hello world"
